language: node_js
notifications:
  email: false
node_js:
  - 'node'
script:
  - npm test
  - npm run build
after_success: if [[ `npm -v` > 4* ]]; then npx codecov; fi
branches:
  only:
    - master
    - /^greenkeeper/.*$/
